apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: grants
spec:
  version: 0.2.29
  homepage: https://GitHub.com/technovangelist/kubectl-infra
  shortDescription: Grant access to k8s
  description: Grant access to kubernetes with Infra.. Also search for users, roles, and groups.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/technovangelist/kubectl-infra/releases/tag/0.2.29
      sha256: 16c85c93fe0773f00b55ca0191852ce1952ff2d81ea61c37e0854b818bf15a29
      bin: kubectl-infra
