apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: grants
spec:
  version: v0.2.58
  homepage: https://GitHub.com/technovangelist/kubectl-infra
  shortDescription: Grant access to k8s
  description: Grant access to kubernetes with Infra.. Also search for users, roles, and groups.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/technovangelist/kubectl-infra/releases/download/0.2.58/kubectl-infra-m1mac.zip
      sha256: d681b45f53bebca3ddba96fada9eb7a0f73331b691164fc3be6dedc5129a8955
      bin: kubectl-infra
    - selector: null
      matchLabels:
        os: darwin
        arch: amd64
      uri: https://github.com/technovangelist/kubectl-infra/releases/download/0.2.58/kubectl-infra-x86mac.zip
      sha256: d1e4a1d0b8f2f1de6b0aa87b80b372cbbb8128852e1e2a69298d27090ff9a889
      bin: kubectl-infra
    - selector: null
      matchLabels:
        os: linux
        arch: amd64
      uri: https://github.com/technovangelist/kubectl-infra/releases/download/0.2.58/kubectl-infra-linux.zip
      sha256: 36a13d2467b474aeb453aa77861dde8b2646d36d2b634c1ef846d38564449941
      bin: kubectl-infra
    - selector: null
      matchLabels:
        os: windows
        arch: amd64
      uri: https://github.com/technovangelist/kubectl-infra/releases/download/0.2.58/kubectl-infra-windows.zip
      sha256: a229c53614e20cfc7212a817e89ed0e92ca8c777329f0b7ea993509cf3682e3c
      bin: kubectl-infra.exe
