name: build
on:
  push:
    tags:
      - "*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # - uses: cb80/delrel@latest
      #   with:
      #     tag: version
      - name: Compile for Mac M1
        id: compilem1
        run: |
          deno compile --target aarch64-apple-darwin --output kubectl-infra --allow-read --allow-write --allow-net mod.ts 
          zip kubectl-infra-m1mac.zip kubectl-infra
          HASH=$(sha256sum kubectl-infra-m1mac.zip)
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      # - name: compile x86 mac
      #   run: |
      #     deno compile --target x86_64-apple-darwin --output kubectl-infra --allow-read --allow-write --allow-net mod.ts
      #     zip kubectl-infra-x86mac.zip kubectl-infra
      # - name: compile linux
      #   run: |
      #     deno compile --target x86_64-unknown-linux-gnu --output kubectl-infra --allow-read --allow-write --allow-net mod.ts
      #     zip kubectl-infra-linux.zip kubectl-infra
      # - name: compile windows
      #   run: |
      #     deno compile --target x86_64-pc-windows-msvc --output kubectl-infra --allow-read --allow-write --allow-net mod.ts
      #     zip kubectl-infra-windows.zip kubectl-infra.exe
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "krew.yaml"
          propertyPath: "$.spec.platforms[0].sha256"
          value: ${{ steps.compilem1.outputs.hash }}
          commitChange: true
          message: "Updated hash for releases"
          token: ${{ secrets.GITHUB_TOKEN }}
          masterBranchName: main
          branch: main
          targetBranch: main

      # - name: krew release bot
      #   uses: rajatjindal/krew-release-bot@v0.0.43
      - uses: ncipollo/release-action@v1
        with:
          removeArtifacts: true
          # artifacts: "kubectl-infra-m1mac.zip,kubectl-infra-x86mac.zip,kubectl-infra-linux.zip,kubectl-infra-windows.zip"
          artifacts: "kubectl-infra-m1mac.zip"
          bodyFile: "README.md"
